### ISSUE TITLE
HD_Instrucción GETCELL VALUE_Exception from HRESULT: 0x80070057 (E_INVALIDARG)_(v20200212T0856)

### ISSUE THREAD

**Issue by CeliaLinares** [FridaSupport/CongnitiveTestingMXTHD#10]
### Caso 1
Usando la sintaxis:
Excel GetCellValue from the worksheet TestData in cell {E4} and save as IsLocal

El log indica:
Error: The parameter is incorrect. (Exception from HRESULT: 0x80070057 (E_INVALIDARG))

### Caso 2
Usando la sintaxis:
Excel GetCellValue from the worksheet TestData in column {E} and row {4} and save as IsLocal

El log indica:
Error: Syntax Error in GetCellValue from the worksheet TestData in column {E} and row {4} and save as IsLocal

**Comment by gantonioid** [comment]
Para el caso 1: estás poniendo `SOAP Excel` ?? quítale el SOAP y a ver qué te marca, porque GetCellValue es instrucción de Excel, no de SOAP

Para el caso 2:
El syntax error es porque le pides la columna E, pero puedes ver en la documentación que le tienes que dar un número.
[http://automationplatform.azurewebsites.net/Readers/Tools/Excelium/GetCellValue](http://automationplatform.azurewebsites.net/Readers/Tools/Excelium/GetCellValue)
![image](https://user-images.githubusercontent.com/9600868/74969366-16e45b00-53e2-11ea-988c-41c6cafc1030.png)

**Comment by CeliaLinares** [comment]
Hola, si son la misma INSTRUCCIÓN pero diferente sintaxis :) solo para que lo tengas en cuenta.
Corregí la descripción del issue, )no escribí SOAP), te comparto los txt de ambos logs.
[log_GetCellValue_SintaxError_0220_GIT011.txt](https://github.com/FridaSupport/CongnitiveTestingMXTHD/files/4232595/log_GetCellValue_SintaxError_0220_GIT011.txt)
[log_GetCellValue_InvalidArg_0220_GIT010.txt](https://github.com/FridaSupport/CongnitiveTestingMXTHD/files/4232593/log_GetCellValue_InvalidArg_0220_GIT010.txt)

**Comment by gantonioid** [comment]
gracias, revisaste con la corrección que te mencioné para la sintaxis?

**Comment by CeliaLinares** [comment]
Solo lo redacté mal aquí en el issue, pero la instrucción original estaba correcta, según el ejemplo que pusiste :)

**Comment by gantonioid** [comment]
No Celia, el log que adjuntas con el nombre "log_GetCellValue_SintaxError_0220_GIT011.txt" dice lo siguiente:
![image](https://user-images.githubusercontent.com/9600868/75000189-4cf5ff00-5423-11ea-8251-ffa4b6daf812.png)

Por favor aplica lo que te estoy diciendo de cambiar esa E por un número.

**Comment by gantonioid** [comment]
Puedes también adjuntar tu excel?

**Comment by CeliaLinares** [comment]
Ya funciona la instrucción.
