### ISSUE TITLE
HD_Instrucción GETCELL VALUE_Syntax Error in GetCellValue_(v20200212T0856)

### ISSUE THREAD

**Issue by CeliaLinares** [FridaSupport/CongnitiveTestingMXTHD#11]
Usando la sintaxis:
Excel GetCellValue from the worksheet TestData in column {E} and row {4} and save as IsLocal

El log indica:
Error: Syntax Error in GetCellValue from the worksheet TestData in column {E} and row {4} and save as IsLocal

**Comment by gantonioid** [comment]
@CeliaLinares voy a dejar un solo ticket dado que se trata de la misma instrucción.
