### ISSUE TITLE
HD_Instrucción SOAP_Data at the root level is invalid. Line 44, position 1 (v20200212T0856)

### ISSUE THREAD

**Issue by CeliaLinares** [FridaSupport/CongnitiveTestingMXTHD#12]
Se indica: Data at the root level is invalid. Line 44, position 1

--SCRIPT--
SOAP url={"http://10.21.92.20:9080/yantrawebservices/services/YIFWebService"} template={"TemplateINNUNO.txt"} headers={"soapAction":""} tls={true} params={"IsLocal":"Foreign","DCoord1":"25.630409","DCoord2":"-100.297204","SourcClass":"8701_WS","TiendaLogeada":"8701","IdItem1":"877891", "UOMItem1":"EA","IdItem2":"995667","UOMItem2":"EA", "IdItem3":"887836","UOMItem3":"EA", "IdItem4":"862125","UOMItem4":"EA"} and save as WSResponse
[log_SOAP_DataAtTheRootLevelIsInvalid_0221_GIT12.txt](https://github.com/FridaSupport/CongnitiveTestingMXTHD/files/4238501/log_SOAP_DataAtTheRootLevelIsInvalid_0221_GIT12.txt)

**Comment by gantonioid** [comment]
Este error es común y ajeno a Frida.

Como buena práctica, te sugiero buscar en la web cuando haya algún mensaje de error.

https://bytes.com/topic/asp-net/answers/663262-web-service-giving-data-root-level-invalid-error

https://stackoverflow.com/questions/8931889/data-at-the-root-level-is-invalid

**Comment by CeliaLinares** [comment]
Corregido, gracias por la info
