### ISSUE TITLE
HD_Instrucción EXCEL SAVE_Error Save TestData_(v20200212T0856)

### ISSUE THREAD

**Issue by CeliaLinares** [FridaSupport/CongnitiveTestingMXTHD#13]
Al agregar la instrucción "Excel Save TestData" o "Excel Save SOMTemplateS001 and close" en el bloque anterior en el que se manipula el mismo archivo se muestra "Error Save TestData"
*Funciona cuando se aísla el fragmento, ocurre cuando la instrucción se repite.
*Si se está cargando correctamente el workbook y la hoja.

**Comment by FaustinoLechuga** [comment]
¿Podrias adjuntar el log.txt de este caso? Asi podremos ver mas a detalle a que se debe esto.

**Comment by CeliaLinares** [comment]
[log_Excel_SaveTestData_0317_GIT013.txt](https://github.com/FridaSupport/CongnitiveTestingMXTHD/files/4344685/log_Excel_SaveTestData_0317_GIT013.txt)

Adjunto el log, gracias!

**Comment by FaustinoLechuga** [comment]
El error indica que hay un problema al cargar el WorkBook
Excel LoadWBook "C:\Users\1027631\Desktop\S001\S001ExcCaptura\SOMTemplateS001.xlsx" as SOMTemplateS001 : Error

Lo que note al revisar el log que este libro SOMTemplateS001 ya lo habias cargado pero no lo cerraste. 

Lo que yo recomendaría es cerrar el libro con la instrucción de CloseWB antes de volverlo a cargar.

**Comment by CeliaLinares** [comment]
El wb lo cargué en la primer sección que lee los valores y lo cerré con Excel Save TestData, cuando no le agrego esa línea, se muestra: Error loading the book, please verify that the document exist or is not corrupted

**Comment by FaustinoLechuga** [comment]
Tal vez no se este usando el Save de la manera adecuada, lo que veo es que TestData es un worksheetkey y por lo tanto puede que esto provoque  que el Save no funcione de manera correcta.

Save <wbkey>

En la sintaxis se muestra de esta manera, siendo el wbkey (WorkBookKey) en tu caso SOMTemplateS001.
Intenta cambiando este parámetro.

Yo utilizaría esta sintaxis para que cierre el libro y lo puedas cargar nuevamente.
Save <wbkey> and close

**Comment by FaustinoLechuga** [comment]
@CeliaLinares ¿Se resolvió la problemática con esto?

**Comment by CeliaLinares** [comment]
Si, resuelto gracias

**Comment by FaustinoLechuga** [comment]
Con lo comentado cierro el Issue.
