### ISSUE TITLE
HD_Duda_Quitar archivos agregados

### ISSUE THREAD

**Issue by CeliaLinares** [FridaSupport/CongnitiveTestingMXTHD#15]
¿Como quito un archivo que se cargo a un script, con la opción Add file?
Gracias

**Comment by FaustinoLechuga** [comment]
Por el momento no hay nada para que tu quites el archivo, pero nos dices que archivo quieres quitar con gusto te podemos ayudar a removerlo.

**Comment by gantonioid** [comment]
@CeliaLinares ?

**Comment by gantonioid** [comment]
Era solo pregunta o requieres que quitemos alguno?

**Comment by CeliaLinares** [comment]
Ocupo la información del issue #16 para especificarles todos los scripts en los que necesitaría que se retiren archivos, gracias

**Comment by CeliaLinares** [comment]
Si ocuparía que se retiraran los archivos siguientes:
1.- Process ID 5003960 archivo DISTANCIAS
2.- Process ID 5590397archivo TemplateWS001 ReqFromSoap
3.- Process ID 1459831 archivo TemplateINNUNO
4.- Process id 8443755 archivo ReqFromSOAP1

Gracias!

**Comment by gantonioid** [comment]
Borrados, ticket atendido
