### ISSUE TITLE
HD_Duda_No abre script específico

### ISSUE THREAD

**Issue by CeliaLinares** [FridaSupport/CongnitiveTestingMXTHD#16]
El script THD GB SOM 002 MAIN no puede abrirse, se cierra la aplicación, ya reinicié el equipo.
En web tampoco se abre el script.

**Comment by gantonioid** [comment]
Cuál es tu ID de proceso? Siempre incluye esta información adicional a tu reporte para poder revisarlo por favor

**Comment by CeliaLinares** [comment]
No sé cual es el id porque no puedo abrir el script.

**Comment by gantonioid** [comment]
Te estoy enviando el update `20200325T0740` para corregir esto; por favor haz la actualización y me comentas

**Comment by CeliaLinares** [comment]
Actualicé la aplicación, ya funciona correctamente gracias!
