### ISSUE TITLE
HD_Duda_Error al actualizar versión

### ISSUE THREAD

**Issue by CeliaLinares** [FridaSupport/CongnitiveTestingMXTHD#17]
En la última actualización al abrir la aplicación, me indica lo siguiente:
![image](https://user-images.githubusercontent.com/60754307/77591048-c5cdf800-6eb4-11ea-88cb-4a53a72820e6.png)

**Comment by FaustinoLechuga** [comment]
Podrias verificar que no haya procesos que se llamen TuringExpo.exe corriendo?

**Comment by CeliaLinares** [comment]
Hoy lo validé y ya abre correctamente, no realicé ninguna acción, abrió normalmente.

**Comment by FaustinoLechuga** [comment]
Perfecto, cerraré el issue, si se vuelve a presentar el mismo error puedes volver a abrir este mismo issue.
