### ISSUE TITLE
HD_Duda_Como quito pausa al script si se cierra el mensaje

### ISSUE THREAD

**Issue by CeliaLinares** [FridaSupport/CongnitiveTestingMXTHD#18]
Buen día, agregué un mensaje para cambiar algo durante el script, pero al dar clic en la pestaña que requiero el mensaje de validación/notificación se cierra y ya no puedo continuar con la ejecución del script, existe alguna otra manera de indicar que se siga corriendo el script?

**Comment by FaustinoLechuga** [comment]
Me podrias brindar mas informacion sobre el problema? En el systemnotify le estas dando click en aceptar o en cancelar?

**Comment by CeliaLinares** [comment]
Buen día, el mensaje dejaba de estar visible cuando se da clic en cualquier lugar de la pantalla (no di clic en el mensaje), por lo que cerré la aplicación, entonces ya ubiqué el mensaje,  posteriormente no pude abrir ya la aplicación hasta reiniciar la máquina.

**Comment by FaustinoLechuga** [comment]
Me podrias compartir la version con la que cuentas? Si puedes tener una llamada para ver esto con mayor detalle me lo podrias informar?

**Comment by CeliaLinares** [comment]
Claro, si ocupas más info me puedes marcar sin problema, pero ahorita por la red no puedo reproducir exactamente el escenario, cambié de instrucción porque ocupaba con urgencia ejecutar el script.
![image](https://user-images.githubusercontent.com/60754307/78289234-11009000-74df-11ea-8c25-7a5e53e025bf.png)

**Comment by RickProductivity** [comment]
@CeliaLinares sigue siendo un problema

**Comment by FaustinoLechuga** [comment]
Lo cierro debido a que no reporta fallo, en caso de se presente de nuevo la anomalía abrir este issue de nuevo.
