### ISSUE TITLE
Uso de DataDriven en un WebService

### ISSUE THREAD

**Issue by raulhgit** [FridaSupport/CongnitiveTestingMXTHD#19]
Buenas tardes compañeros.

Tengo un Script en el cual utilizo la función SOAP para utilizar un WebService, Esto es para crear ordenes de compra enviando los datos desde un XML. 

Ya tengo cargado mi archivo excel en datadriven con los datos que se requieren completar en el XML.  Por Ejemplo:

*RetailStoreID>**ddTiendaRemisiona**</RetailStoreID*

Como se puede ver en la imagen de datadriven, se requiere que el valor 8760 de la columna **ddTiendaRmisiona** se substituya en el XML previamente cargado en el Script como RetailTransactionUpdate.txt

En el XML ya intente colocando la etiqueta ddTiendaRemisiona dentro de las llaves dobles y triples <<ddTiendaRemisiona>> <<<ddTiendaRemisiona>>> , también intente previamente asignar el valor a una variable definida pero creo que como está en comillas " " le da el valor del nombre ddTiendaRemisiona y no el valor que debe ser 8760.

Solicitando su apoyo para que en resumen el valor del datadriven se substituya en el XML cargado al Script.

Como Nota, la ejecución la realizo en modo Listener y ejecuto desde Cognitive testing. La segunda imagen de Turing es porque desde ahi subí el archivo txt que contiene el XML.

![image](https://user-images.githubusercontent.com/56734739/85064978-02d31f00-b172-11ea-8b8d-1f97131c32ab.png)

![image](https://user-images.githubusercontent.com/56734739/85065370-a7edf780-b172-11ea-807f-0df16b4b3036.png)

**Comment by gantonioid** [comment]
Ya pudiste?

Armé un script mínimo para correr SOAP con data driven y aquí está
Main:
```
DefineVariable type "string" as "whatever" with the value "<<value>>"
SOAP url={"http://LSTKMY241297:8088/mockNumberConversionSoapBinding"} template={"request.txt"} and save as soapres
```
archivo del request:
![image](https://user-images.githubusercontent.com/9600868/90447352-bc823980-e0a8-11ea-966b-0f8d26271d9a.png)


El truco, creo que está en que en la página de Cognitive solo reconoce variables de data driven en el script principal. Es por eso que requieres una variable auxiliar. En este ejemplo mi variable para el data driven (le alimento valores con el excel) se llama **value**, y mi auxiliar la nombré **whatever**. 
![image](https://user-images.githubusercontent.com/9600868/90447830-bf315e80-e0a9-11ea-93db-c58ed97d8ef2.png)
Con eso, luego la instrucción SOAP se encargará de hacer el reemplazo en tu template XML de la llamada al webservice durante la ejecución.
