### ISSUE TITLE
Ejecución de pruebas multi-browser

### ISSUE THREAD

**Issue by JorgeSalazarTHD** [FridaSupport/CongnitiveTestingMXTHD#2]
Cubrir la automatización de pruebas para las aplicaciones Fleet y RH Corp, que no utilizan chrome y que en su lugar utilizan otros navegadores como Internet Explorer, Microsoft Edge. También cubrir las pruebas de compatibilidad de ecommerce con los exploradores mencionados y adicionalmente FireFox

**Comment by gantonioid** [comment]
Se ha incorporado este elemento de configuración para seleccionar el user-agent que se va a usar para las pruebas con instrucciones Web2
![image](https://user-images.githubusercontent.com/9600868/74372567-833adb00-4da0-11ea-93df-c051b3212f51.png)
