### ISSUE TITLE
Función Select Value borra simbolo de igual (=)

### ISSUE THREAD

**Issue by raulhgit** [FridaSupport/CongnitiveTestingMXTHD#20]
Cuando utilizas la función Select value en el editor de texto de Cognitive por ejemplo:

Web2 Select value="Valor" in selector"#selector"

al grabar el script y ejecutarlo marca un error de sistaxis i lexical errror.  Y al revisar el código se detecta que se elimina el simbolo de igual, quedando asi la sintaxis.

Web2 Select value "Valor" in selector"#selector"

Podrían apoyarme porfavor a revisar este bug.

**Comment by jorgebibarra** [comment]
No encontramos, el error.
No es porque estas guardando mal la instrucción? Web2 Select value="Valor" in **selector"#selector"** te falta el igual

**Comment by raulhgit** [comment]
Voy a ver si puedo adjuntar un video corto, dame unos minutos

**Comment by raulhgit** [comment]
No me permite adjuntar el video, Les envio por correo .

**Comment by raulhgit** [comment]
[Select Value.zip](https://github.com/FridaSupport/CongnitiveTestingMXTHD/files/5139152/Select.Value.zip)
Parace que en formato Zip si me permite.

**Comment by raulhgit** [comment]
[Select ValueMP4.zip](https://github.com/FridaSupport/CongnitiveTestingMXTHD/files/5139176/Select.ValueMP4.zip)
Lo comparto en formato mp4

**Comment by jorgebibarra** [comment]
Ya quedó resuelto.
