### ISSUE TITLE
Error en RunProcess a un script que utiliza funcion SOAP

### ISSUE THREAD

**Issue by raulhgit** [FridaSupport/CongnitiveTestingMXTHD#21]
Al ejecutar el proceso id 6392508 o el proceso id 9531174 por separado se ejecutan correctamente pero si cualquiera de los dos  se mandan llamar con la función RunProcess desde otro Script aparece un error 404 Not Found en la respuesta recibida por la función SOAP.

En la arquitectura usada en THD se tiene un script padre o end to end donde se ejecutan los scripts hijos o módulos y para este escenario cuando se llama cualquier script que utilize la funcion SOAP marca el error de la imagen.

Aclaro que si se ejecuta de manera individual cada uno funcionan correctamente.

![image](https://user-images.githubusercontent.com/56734739/97510142-bd0d3b00-1949-11eb-9c43-8823449a3c5b.png)

Gracias de antemano por el apoyo. Saludos.

**Comment by AlanArteche** [comment]
Buenas tardes, @raulhgit . No hemos se ha podido replicar el mismo error utilizando 2 procesos nuestros y otro endpoint para lallamada SOAP.

![image](https://user-images.githubusercontent.com/48565879/98998719-338a6b00-24fc-11eb-9762-1b04d45a46d3.png)

¿Hay problema si se hacen llamadas de GetSplitShippingPriceRequest a ese endpoint para hacer pruebas usando los datos de data driven del proceso?

**Comment by RickProductivity** [comment]
@raulhgit cuando puedas nos comentas? O ya se resolvió ?

**Comment by raulhgit** [comment]
Buenos días, lo estoy revisando.

**Comment by raulhgit** [comment]
Buenos días, 

Pensando en que no puedan replicar el escenario por que no tienen VPN a HomeDepot, Hice un ejemplo consumiendo un WS público muy sencillo que suma 2 números y regresa el resultado.

Se presenta el mismo error "The remote server returned an error: (404) Not Found."

El proceso que tiene tiene la funcion SOAP y llama al WS es el 7761190 el cual si se ejecuta de forma individual y trae como resultado el número 2 porque la operación es 1+1

Cree otro Test Case End to End con el id 7656269 donde desde ahi mando llamar el 7761190  y me regresa el error 404 cuando lo ejecuto.

Adjunto el resultado de la prueba cuando se ejecuta individual y cuando es ejecutado desde otro proceso.
[log-2020112312092469.txt](https://github.com/FridaSupport/CongnitiveTestingMXTHD/files/5584908/log-2020112312092469.txt)

[log-2020112311581637.txt](https://github.com/FridaSupport/CongnitiveTestingMXTHD/files/5584882/log-2020112311581637.txt)

Si es posible me pueden contactar en cualquier horario por Teams y hacemos una prueba en línea.

Gracias por el seguimiento.

**Comment by AlanArteche** [comment]
La VPN de HomeDepot no es necesaria para replicar el problema, yo igualmente hice mi prueba con un WS público sencillo. Revisaré la nueva información que compartes y trataré nuevamente de replicar el problema. ¿Cómo te podría contactar por Teams en caso de que sea necesario? 

Saludos.

**Comment by raulhgit** [comment]
Hola Alan, estoy como Raul Humberto Gonzalez Guajardo y mi correo es raulh.gonzalez@softtek.com

**Comment by AlanArteche** [comment]
Ya se logró detectar con exactitud dónde y por qué ocurre este bug así que se procederá a analizar cómo se le puede dar solución.

**Comment by AlanArteche** [comment]
@raulhgit Listo, ya se implementó una solución. ¿Está bien si te envío un update de versión para que realices nuevamente tu prueba? Te recomendaría que hicieras la prueba en procesos nuevos ya que pudiera haber algún problema debido a cómo estaba implementada la lógica hasta el momento.

**Comment by raulhgit** [comment]
> @raulhgit Listo, ya se implementó una solución. ¿Está bien si te envío un update de versión para que realices nuevamente tu prueba? Te recomendaría que hicieras la prueba en procesos nuevos ya que pudiera haber algún problema debido a cómo estaba implementada la lógica hasta el momento.

De acuerdo con la actualización.

**Comment by AlanArteche** [comment]
@raulhgit Listo, ya te enviado el update para que lo aceptes. Adicionalmente, te pediría que eliminaras completa la carpeta Local de tu Turing para evitar conservar alguna inconsistencia. Espero los resultados de la prueba para que podamos cerrar este ticket.

Saludos.

**Comment by raulhgit** [comment]
Buenos días Alan, una buena y una mala. La buena ya puedo mandar llamar la función SOAP desde otro Test Case y ejecuta correctamente.  La mala, en HomeDepot la intención de este proceso es que desde una sola ejecución del script podamos crear "N" cantidad de ordenes de compra y para eso utilizamos DataDriven. Entonces me doy cuenta que si utilizo variables en el XML con los < > picoparentesis, me arroja el siguiente error.

11/24/2020 10:01:30 AM - SOAP url={"http://10.21.96.17:95/Sales/InterfacesSales.asmx?WSDL"} template={"GetSplitShippingPriceRequest.txt"} params={"ddOrdens":"<<<ddOrdens>>>"} and save as WSResponse : Running
11/24/2020 10:01:31 AM - Error, sendig SOAP call
11/24/2020 10:01:31 AM - Error : Name cannot begin with the '<' character, hexadecimal value 0x3C. Line 9, position 38.
11/24/2020 10:01:31 AM -    at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.Throw(String res, String[] args)
   at System.Xml.XmlTextReaderImpl.ParseQName(Boolean isQName, Int32 startOffset, Int32& colonPos)
   at System.Xml.XmlTextReaderImpl.ParseElement()
   at System.Xml.XmlTextReaderImpl.ParseElementContent()
   at System.Xml.XmlTextReaderImpl.Read()
   at System.Xml.XmlLoader.LoadNode(Boolean skipOverWhitespace)
   at System.Xml.XmlLoader.LoadDocSequence(XmlDocument parentDoc)
   at System.Xml.XmlLoader.Load(XmlDocument doc, XmlReader reader, Boolean preserveWhitespace)
   at System.Xml.XmlDocument.Load(XmlReader reader)
   at System.Xml.XmlDocument.LoadXml(String xml)
   at MixedReader.MixedExecute.CallSOAP(String procID, String url, String templatePath, String parameters, String user, String pass, String host, String headers, Boolean tls) in C:\Users\alanm.gonzalez\Source\Repos\AutomationPlatform\MixedReader\MixedExecute.cs:line 10590
   at MixedReader.MixedExecute.SOAP(String action, String procID) in C:\Users\alanm.gonzalez\Source\Repos\AutomationPlatform\MixedReader\MixedExecute.cs:line 10495
11/24/2020 10:01:31 AM - SOAP url={"http://10.21.96.17:95/Sales/InterfacesSales.asmx?WSDL"} template={"GetSplitShippingPriceRequest.txt"} params={"ddOrdens":"<<<ddOrdens>>>"} and save as WSResponse : Error
11/24/2020 10:01:31 AM - FRIDA Process6392508 : Error
11/24/2020 10:01:31 AM - RunProcess 6392508 : Error

**Comment by AlanArteche** [comment]
Ok, estaré revisando si el problema es uno de sintáxis con la instrucción SOAP o si es otro problema similar al anterior.

**Comment by AlanArteche** [comment]
Efectivamente el problema es como el anterior donde, en caso de haber información proveniente de Data Driven, sólo se tomaría del proceso padre. El diseño actual de la arquitectura permitiría que, en este caso, si cargas las variables de Data Driven en el proceso padre, se podrían utilizar en los procesos hijos; pero entiendo que esto no es una solución completa ya que podrían llamarse a ejecutar más procesos hijos dentro del padre y podría requerirse que algunos de esos procesos se ejecuten un número diferente de veces.

Tendrá que consultarse con el equipo cuál es la mejor forma de dar solución a este problema ya que requiere cambios mayores.

**Comment by AlanArteche** [comment]
Se determinó que no se modificará la arquitectura que involucra a nuestra API y a Turing. Afortunadamente hay un workaround ejecutando los procesos hijos de manera normal, cargando la información de sus Data Driven con instrucciones de FRIDA y con un ciclo foreach determinar cuántas veces ejecutar una serie de instrucciones.

A continuación muestro un script de ejemplo.

```
##Al no ser un proceso hijo que podría requerir un número de información proveniente de Data Driven diferente
##a otros procesos hijos, se recomienda hacer las iteraciones y uso de la información a través de un ciclo foreach

##Leemos el archivo datadriven.txt

LoadDataDrivenList and save as "DataDrivenList"

##Definimos un ciclo foreach para que haya una ejecución por cada fila de datos de Data Driven.

DefineVariable type "int" as "Iteracion" with the value "1"

foreach DataRow in DataDrivenList {

##Mensaje de número de iteración.

Message Iteración Número <<<Iteracion>>>

##Cargamos a las variables los valores del siguiente renglón de Data Driven.

LoadDataDrivenObject <<<DataRow>>>

##Ejecución del proceso.

RunScript RutinaProceso.txt

Iteracion++

}

```

La serie de instrucciones del proceso como tal las coloqué en un script por separado para darle más limpieza solamente.

```
##Este es el script de mi proceso para tenerlo más limpio.

DefineVariable type "string" as "UrlWebService" with the value "http://www.dneonline.com/calculator.asmx?WSDL"
DefineVariable type "string" as "ddOrdens" with the value "12345"
SOAP url={"<<<UrlWebService>>>"} template={"calculator.txt"} params={"ddOrdens":"<<<NumeroCuenta>>>"} and save as WSResponse
```

Adjunto un log donde puedes ver el resultado de ejecutar este proceso hijo que hace llamada SOAP a través de RunProcess en el proceso padre.

[log-2020112520085691.txt](https://github.com/FridaSupport/CongnitiveTestingMXTHD/files/5599038/log-2020112520085691.txt)

Otra forma de verlo es como si estuviéramos haciendo a un lado Data Driven como tal ya que el proceso padre, quien en teoría debería proveer a los procesos hijos de los parámetros necesarios, es un proceso que no requiere de Data Driven.

En otras palabras, Data Driven toma la información de un único proceso, el padre, y tiene capacidad de heredar esta información a los hijos, los cuales no son capaces de tomar su propia información.

El único inconveniente que veo, si es que así lo consideras, es que con esta alternativa sólo se generaría un único Log por la ejecución del proceso hijo y sus iteraciones.

Espero tu opinión sobre esta solución, @raulhgit .

**Comment by raulhgit** [comment]
Alan, gracias por el seguimiento. Para este escenario no habría problema por tener un solo log.  Voy a hacer una prueba como el ejemplo que compartes.
