### ISSUE TITLE
Page could not be reached.

### ISSUE THREAD

**Issue by raulhgit** [FridaSupport/CongnitiveTestingMXTHD#22]
Al abrir la página desde cognitve "https://venprtlappdevwv:2901/#/loginInitial" del portal de proveedores de Home Depot excede el tiempo de respuesta y regresa en error.

FRIDA Process 3141232 : Running
11/10/2020 2:47:19 PM - Web2 GoTo "https://venprtlappdevwv:2901/#/loginInitial" : Running
11/10/2020 2:47:19 PM - Running browpet-engine
11/10/2020 2:48:56 PM - {"error":"Page could not be reached...TimeoutError: Navigation Timeout Exceeded: 90000ms exceeded"}
11/10/2020 2:48:56 PM - Web2 GoTo "https://venprtlappdevwv:2901/#/loginInitial" : Error
11/10/2020 2:48:56 PM - FRIDA Process3141232 : Error

Al abrir la página en chrome fuera de cognitive abre en 2 segundos.
![image](https://user-images.githubusercontent.com/56734739/98737161-71a45500-236b-11eb-9c6f-3c3d237bb2d0.png)

**Comment by RickProductivity** [comment]
@ErlikC nos ayudas ?

**Comment by RickProductivity** [comment]
Se resolvió?

**Comment by raulhgit** [comment]
Hola buenos días, si se resolvió. Gracias
