### ISSUE TITLE
Conexión a base de datos no trae resultados.

### ISSUE THREAD

**Issue by raulhgit** [FridaSupport/CongnitiveTestingMXTHD#23]
Hola buenas tardes,

Tengo un test case muy sencillo donde hago una conexión a BD y una consulta Select. Al ejecutar el TC no marca error sin embargo la variable lista no muestra resultado, se queda en blanco. Este es el código

DB Connect to DB connectionstring={Server=10.21.92.71;Database=mi9_mms_hm_dev;User Id=sql-dev;Password=sql-dev;} name={MMSDB}

DB RunOutputQuery {SELECT * FROM mi9_mms_hm_dev.dbo.HDM_AP_Department} in {MMSDB} as {TopList}

Adjunto el archivo log de salida.
[log-2020120712120718.txt](https://github.com/FridaSupport/CongnitiveTestingMXTHD/files/5655669/log-2020120712120718.txt)

Estoy siguiendo la documentación del Reader para base de datos y quisiera saber si me pueden apoyar con un ejemplo de conexión y consulta para comparar los parámetros y detectar un error.

Gracias.

**Comment by gantonioid** [comment]
Se ve todo en orden con el script. Para confirmar, puedes hacer dos cosas:
- Ver si el script arroja algo ejecutándolo en el SQL_Server tal cual (una sola línea)
- Pasar tu script a un archivo txt aparte, y cambiar tu instrucción RunOutputQuery a la sintaxis en la que se pone el archivo txt, no el script SQL
`RunOutputQuery {miOtroArchivo.txt} in {MMSDB} as {TopList}`

**Comment by gantonioid** [comment]
Además, te comento que debido a que RunOutputQuery puede potencialmente traer una enorme cantidad de resultados (y saturar el log). Se dejó de imprimir el resultado del query en el archivo log.txt

Podrías comprobar el funcionamiento del query con un ciclo, o con un [CountItems](https://frida-admin.web.app/Documentation/Readers/Mix%20Reader/CountItems)
`CountItems in TopList and save as cuenta`

**Comment by raulhgit** [comment]
HOla Toño, me di cuenta que no muestra resultados pero tengo que Parsear la variable de salida para poder ver los resultados,

Por ejemplo:
ParseVariable "TopList" and save as "varlist"

De esa forma puedo ver en un string los datos

12/8/2020 10:16:22 AM - Se agrego una nueva variable : 
Var Name : varlist
Value : [["107431","32.00","8061098405","8724"],["107431","32.00","8061098405","8724"],["107431","32.00","8061098405","8724"],["805034","30.00","8061098405","8724"],["805034","30.00","8061098405","8724"]]


Ahora lo que estoy tratando de hacer es descomponerlos en una lista separada por comas o ver de que manera puedo obtener la información específica que necesito.

Gracias, saludos.

**Comment by gantonioid** [comment]
es una lista bidimensional... por lo tanto funciona como Excel ReadRows. Puedes iterar
```
foreach row in TopList {
    #Esto es una linea de la tabla. Por ejemplo:
    # ["107431","32.00","8061098405","8724"]
    Message <<<row[2]>>>
    #Arrojaría el valor 8061098405
}
```

**Comment by raulhgit** [comment]
Muchas gracias por el apoyo, con la iteración de foreach se obtienen los valores.
