### ISSUE TITLE
Error 404 URL de WebService

### ISSUE THREAD

**Issue by raulhgit** [FridaSupport/CongnitiveTestingMXTHD#24]
Buenos días,

Para las Suites de HomeDepot se tienen diseñados Test Case End to End (TC Padres) donde se mandan llamar por medio de la función RunProcess los Test Cases (hijos) que se requieran usar. 

Cuando se manda ejecutar un Test case hijo atravez de un TC padre que utiliza la funcion SOAP regresa el error 404 Not Found. Se probó con varios WebService y el resultado es el mismo.

Si se ejecuta solamente el TestCase Hijo de manera individual la función SOAP funciona correctamente.

Favor de contactarme paraver un ejemplo ya que para hacer las pruebas es necesaria la conexión por VPN,

**Comment by gantonioid** [comment]
Es el mismo problema que #21  ?? 
@AlanArteche

**Comment by AlanArteche** [comment]
Sí me suena a que es exactamente el mismo problema pero ya había quedado resuelto. @raulhgit ¿Es el mismo problema que se presentaba en el ticket #21? Esn ese caso llegamos a probar con un Web Service público sin necesidad de VPN
