### ISSUE TITLE
Cambio de Idioma en Chromium

### ISSUE THREAD

**Issue by raulhgit** [FridaSupport/CongnitiveTestingMXTHD#25]
Buenas tardes, para las pruebas de reportes en el sistema de Tienda SMS se requiere que Chrome o en este caso Chromium que utiliza Frida, esté configurado en idioma Español

![image](https://user-images.githubusercontent.com/56734739/128233470-6466e0eb-6c57-434a-b8e5-da2b04a64019.png)

**Comment by raulhgit** [comment]
Actualmente en cada ejecución el idioma seleccionado por default en Chromium siempre es Inglés y no es compatible con los reportes de la Tienda.

**Comment by gantonioid** [comment]
Ayer se compartió una instrucción beta `SetLocale`. esperamos resultados de la prueba.

**Comment by raulhgit** [comment]
Hola buenos días, Se actualizó el Engine con la nueva versión que utiliza la función SetLocale.

Aun así en la ejecución de la prueba en Chromium se sigue manteniendo el lenguaje en Inglés.  Adjunto un video en el cual muestro el sitio en Chrome Español y su comparativo ejecutado desde Cognitive donde se mantiene el lenguaje Inglés aun utilizando la función.


https://user-images.githubusercontent.com/56734739/128545265-0cbd2939-43f6-4fb5-981d-e408f40737c1.mov

**Comment by andresCruzF** [comment]
Hola @raulhgit 
Te comparto una nueva version del engine de Bropwet en la cual se retira la instruccion SetLocale al no cumplir con el requerimiento y se genera una nueva funcion con el nombre de SetLanguage de la cual coloco su documentacion 

**SetLanguage** 
Instrucción nueva (Turing/MixedReader) para cambiar una variable 'language' que se requiere configurar antes de abrir el exe de browpet
 
Ejemplos :

- Web2 SetLanguage "pt-br,pt"
Web2 GoTo "https://www.google.com"
SystemNotify Type "Notification" with message "Checar idioma"

- Web2 SetLanguage "ps-mx,es"
Web2 GoTo "https://www.google.com"
SystemNotify Type "Notification" with message "Checar idioma"

- Web2 SetLanguage "en-us,en"
Web2 GoTo "https://www.google.com"
SystemNotify Type "Notification" with message "Checar idioma"

[browpet-engine.zip](https://github.com/FridaSupport/CongnitiveTestingMXTHD/files/6947939/browpet-engine.zip)

**Comment by raulhgit** [comment]
Gracias por el apoyo, lo voy a validar.

**Comment by andresCruzF** [comment]
De igual forma Raul es necesario realizar un update de Turing , es posible asignarte una nueva version a tu usuario para que puedas realizar pruebas ?

**Comment by raulhgit** [comment]
Si, sin problema

**Comment by andresCruzF** [comment]
Perfecto se te asigno la version 20210806T2138 con los cambios correspondientes, de igual forma te comparto un script de pruebas. Asi mismo te comento que en caso de querer cambiar el idioma del navegador una vez iniciado browpet es necesario realizar un dispose.
```

SetLanguage "en-us,en"
Web GoTo "https://www.google.com"
Web Navigation
Web Sleep 3000
Web Dispose

Web SetLanguage "es-mx,es"
Web GoTo "https://www.google.com"
Web Navigation
Web Sleep 3000
Web Dispose
```

**Comment by raulhgit** [comment]
Hola buenos días, Ya actualicé la versión de Turing pero algo sucede que cualquier Script que intento ejecutar ya sea en Turing Desktop o desde Cognitive no se abre el Engine y se queda en proceso de ejecución y no avanza. Tengo que cerrar Turing y volver a abrir.

**Comment by AlanArteche** [comment]
Ya se tuvo una sesión y se harán un par de pruebas para corroborar la instrucción en la versión de Turing así como el cambio en Browpet.

**Comment by AlanArteche** [comment]
Listo, Raúl ya no tuvo problemas para ejecutar procesos que utilicen Browpet, sólo queda pendiente que confirme de primera mano el funcionamiento de SetLanguage para que se puede cerrar este ticket. Quedamos al pendiente.

**Comment by raulhgit** [comment]
Muchas gracias por el apoyo, con la última actualización de Engine y Turing que compartió Alan se logró cambiar el idioma de Chromium.
