### ISSUE TITLE
FRIDA Turing sin acceso

### ISSUE THREAD

**Issue by NancyArias** [FridaSupport/CongnitiveTestingMXTHD#27]
Hola equipo estoy ingresando con mi cuenta de dominio pero me sale un mensaje relacionado a que no tengo acceso.
Podrian apoyarme por favor.
user:1018922@homedepot.com.mx
<img width="280" alt="2022-01-28_15h15_55" src="https://user-images.githubusercontent.com/98622535/151632584-f7568038-3c32-4f54-bf2a-e23eb565fcde.png">

Agrego el archivo LOG
[log.txt](https://github.com/FridaSupport/CongnitiveTestingMXTHD/files/7962497/log.txt)

**Comment by NancyArias** [comment]
Hola Equipo, continuo sin acceso a FRIDA Turing con mi usuario 1018922@homedepot.com.mx
<img width="277" alt="image" src="https://user-images.githubusercontent.com/98622535/151839470-02ff0b38-3eb0-4dd8-9f8b-fec4e218e9d4.png">

**Comment by andresCruzF** [comment]
@NancyArias 

Se asocio al usuario una segunda contraseña validando que mediante esta se pueda ingresar a las aplicaciones 

![image](https://user-images.githubusercontent.com/49708627/152249251-83cef6d8-f7ac-460e-9e47-1aadc40fd9ca.png)

**Comment by NancyArias** [comment]
Se reviso exitosamente el detalle.
