### ISSUE TITLE
Turing modo escucha

### ISSUE THREAD

**Issue by AbdielMoyeda** [FridaSupport/CongnitiveTestingMXTHD#28]
Buen dia

el detalle que presenta Turing es que se cierra al momento de trabajar con el desde Azure y de igual forma la opcion de escucha se desactiva por si sola despues de unos minutos

Gracias por su apoyo

**Comment by ErlikC** [comment]
Hola, a que te refieres con el modo escucha? Es el turing Watcher? que versión de Turing tienes?
Tienes forma de reproducirlo? Si es así una vez que se cierra turing, puedes revisar el visor de eventos de windows, por favor?
![image](https://user-images.githubusercontent.com/60276982/154117802-789710ba-6946-4d53-a251-2736d1ac89e6.png)

Habría que buscar en Registros de Windows > Aplicacion > Buscar
![image](https://user-images.githubusercontent.com/60276982/154119973-70758419-090a-4996-95e3-fca606c8c03a.png)

Y buscando Turing, ahi imagino que puedes encontrar el registro dejado por la aplicación al momento de cerrarse.

**Comment by ErlikC** [comment]
sigue pendiente este error?

**Comment by ErlikC** [comment]
Como lo comentaste por correo, el problema esta resuelto.
