### ISSUE TITLE
Browpet en navegado Chrome

### ISSUE THREAD

**Issue by NancyArias** [FridaSupport/CongnitiveTestingMXTHD#29]
Al instalar la extension de Browpet en chrome, nos impide realizar descargas.
<img width="444" alt="image" src="https://user-images.githubusercontent.com/98622535/152250487-200dea75-13b6-4cd8-8789-91327928703c.png">

**Comment by gantonioid** [comment]
Puedes dar más detalles? cuándo sucede?

Te refieres a que tienes la extensión instalada, y ahora tu Chrome ya no permite descargas?
O es durante la ejecución de la automatización que no se descargan los archivos?

**Comment by NancyArias** [comment]
Hola Antonio,

El detalle es cuando tenemos la extension instalada, al momento de descargar algo marca error.
Lo revisamos en dos computadoras y sucedia lo mismo, le comartimos a Andres y Marino el detalle por correo en su momento.
La version de chrome que tenemos es:
<img width="348" alt="image" src="https://user-images.githubusercontent.com/98622535/154149910-45439d8d-ef14-4e56-aedb-aff42cd93dd5.png">

**Comment by gantonioid** [comment]
Dejo el resultado de mi prueba
- Extensión instalada desde cero con el FRIDA Installer
- Chrome settings -> Extensions -> Load unpacked -> carpeta de la extensión que acabo de desargar y descomprimir
- Descarga archivos sin problema
![image](https://user-images.githubusercontent.com/9600868/154184838-434dfafa-b6d2-4be2-8525-17e82cf6c465.png)

**Comment by NancyArias** [comment]
Hola Antonio, con gusto podemos verlo por llamada nuevamente...
Esto ya se habia revisado con el equipo (Mariano y Andres)
te comparto los pantallazos nuevamente ahorita que instale la extension de Browpet en mi navegador:

<img width="957" alt="image" src="https://user-images.githubusercontent.com/98622535/154307025-486a0500-70a4-48e5-b02f-a5faa545bec0.png">

EVIDENCIA AL MOMENTO DE REALIZAR DESCARGAS DE CUALQUIER TIPO
descarga de recorder:
<img width="962" alt="image" src="https://user-images.githubusercontent.com/98622535/154307094-c4cd9773-11ed-49ac-b723-731e39aae83f.png">

Descarga de documentos CSV, XML...
<img width="951" alt="image" src="https://user-images.githubusercontent.com/98622535/154306998-b97e785d-80d6-4615-88fd-053eebdbd73f.png">

Veo este error dentro de la extension de Browpet
<img width="501" alt="image" src="https://user-images.githubusercontent.com/98622535/154307291-dbeb8d5d-c1b8-4c18-b3c8-512cbeed66f6.png">

Quito la extension de Browpet
<img width="297" alt="image" src="https://user-images.githubusercontent.com/98622535/154307368-ce7359d0-bc4e-456f-83fe-072531f1500d.png">

y ahora si las descargas se realizan exitosamente

**Comment by NancyArias** [comment]
Hola equipo, algun detalle/update?

**Comment by NancyArias** [comment]
Hola Equipo, tendran algun update?

**Comment by Jorgegarcia197** [comment]
Hola Nancy, 

Estuve tratando de replicar el issue descargando tu version de chrome junto con la extensión de Browpet Recorder para ver cuál podría ser la causa del problema.

![version_chrome](https://user-images.githubusercontent.com/46676143/155563609-a3754264-b0f6-44f5-bbe3-6cd7a2c4a2ee.jpg)

Sin embargo, intentando varios sites, tanto en OneDrive, como GoogleDrive, directamente bajando imagenes de Google e incluso un portal hecho por el equipo y no tuve ningún problema al descargar archivos con la extensión abierta. 

Te anexo las imágenes 
## Ejemplo de OneDrive
![downloads](https://user-images.githubusercontent.com/46676143/155564362-16707616-3e66-42ec-b6fe-c58d9706f279.jpg)
## Ejemplo de Google Drive
![google_drive_download](https://user-images.githubusercontent.com/46676143/155564430-eff43f5a-9522-4ed0-9bcf-7ae9ac772d54.jpg)
## Ejemplo directo de google images 
![google_images](https://user-images.githubusercontent.com/46676143/155564601-f88cd97d-9c0a-4c5a-b8d1-4ae479e70a41.jpg)
## Ejemplo Flight Control 
![flight_control](https://user-images.githubusercontent.com/46676143/155564706-1392f194-4036-4eb0-9686-494f3e021cc9.jpg)

Lo que te quería comentar era si podiamos tener una sesión para verlo en vivo el problema y de ser posible esta sesión, cómo buscarte dentro de Teams.

**Comment by NancyArias** [comment]
Hola Jorge buen día,

Estoy en teams como Nancy Arias, tu me dices para poder verlo enconjunto.
Este detalle igual le paso a Abdiel Moyeda con su equipo al tener instalada la extension de Browpet dejo de permitirle realizar descargas.

**Comment by RickProductivity** [comment]
Pudieron Revisar el Tema ?

**Comment by NancyArias** [comment]
Hola Rick, no no hemos recibido algun meeting por parte del equipo para revisarlo.
Continuamos al pendiente

**Comment by Jorgegarcia197** [comment]
Como se comentó durante la sesión de hoy (2/Marzo/22): El issue relacionado a las descargas por parte de la extensión es debido a una cuestión de permisos de navegador por parte de seguridad. Se probó desactivando esos agentes de seguridad y se logró tener la descarga exitosa de archivos con la extensión habilitada desde el equipo de @NancyArias
