### ISSUE TITLE
Activar MODO SILENCIOSO en Azure 

### ISSUE THREAD

**Issue by NancyArias** [FridaSupport/CongnitiveTestingMXTHD#30]
Queremos realizar las ejecuciones de los pipelines desde azure, pero que estos no esten ejecutandose en pantalla. 
Nos podrian apoyar compartiendonos los pasos para activar el modo silencioso en azure, recordamos que era una configuracion que se realizaba por variable o parametro.

**Comment by ErlikC** [comment]
Hola.
En el llamado se debe poner "Headless": "True" o  "Headless": "False", si no se pone nada por default es false.

**Comment by NancyArias** [comment]
Hola Erlik, esta especificacion de llamado lo indicamos en Azure en la ejecucion del pipeline? o va en alguna especificacion del codigo (automatizacion en FRIDA)?

**Comment by ErlikC** [comment]
Si lo ejecutas de este modo con el pipeline, solo es necesario activar la opción de headless.
![image](https://user-images.githubusercontent.com/60276982/154128337-e8f48dd9-0902-40ec-8e7a-c06e0bed4743.png)

**Comment by NancyArias** [comment]
Una disculpa Erlik pero no veo la opcion de HEADLESS EXECUTION
<img width="807" alt="image" src="https://user-images.githubusercontent.com/98622535/154129017-d20dfebd-8cd4-41d8-85ce-15c7060b25b2.png">

**Comment by ErlikC** [comment]
Ya revisé con el equipo. Se va a publicar esa versión para que puedas ver el campo.

**Comment by NancyArias** [comment]
Excelente, gracias Erlik.
Continuo al pendiente para validarlo.

**Comment by NancyArias** [comment]
@ErlikC  tendras algun update sobre la publicacion de version con la propiedad "Headless excecution"?

**Comment by NancyArias** [comment]
Hola equipo, tendran algun update?

**Comment by ErlikC** [comment]
Hola Nancy, 
se liberó la versión del FRIDA Task.

**Comment by NancyArias** [comment]
Listo, GRACIAS!
<img width="957" alt="image" src="https://user-images.githubusercontent.com/98622535/154975628-21a7560d-ad51-460f-a36b-369414a4ca2d.png">
