### ISSUE TITLE
Turing

### ISSUE THREAD

**Issue by AbdielMoyeda** [FridaSupport/CongnitiveTestingMXTHD#31]
Solicito por favor de su apoyo ya que surgió un detalle con Turing ya que al memento de abrirlo me aparece una ventana con un mensage de info

**Comment by ErlikC** [comment]
Hola puedes dar mas detalle del problema porfavor
si tienes log o applog ayudaria mas

**Comment by RickProductivity** [comment]
No podrías compartir el Mensaje también ?

**Comment by ErlikC** [comment]
Sigue sin resolverse este ticket?

**Comment by AbdielMoyeda** [comment]
Ya esta resuelto, por correo comunique que estaba solucionado , gracias Erlik
