### ISSUE TITLE
Al presionar el boton de schedule la aplicación turing se cierra.

### ISSUE THREAD

**Issue by raulhgit** [FridaSupport/CongnitiveTestingMXTHD#4]
Despúes de seleccionar una automatización se abre un menú de opciones del lado izquierdo y al dar click en schedule la aplicación turing se cierra.

![image](https://user-images.githubusercontent.com/56734739/69560297-241fb400-0f71-11ea-9578-8933b8026105.png)

**Comment by RickProductivity** [comment]
Que sistema operativo tienes ??

**Comment by raulhgit** [comment]
Windows 10

**Comment by raulhgit** [comment]
Hola buenas tardes, en la cuenta de HomeDepot se requiere programar la ejecución de un script por la mañana todos los dias y al presionar el botón de schedule se cierra la aplicación Turing. 

¿Se tiene un avance sobre este caso ?

**Comment by gantonioid** [comment]
Con el update de THD se resolvió este problema?

**Comment by FridaSupport** [comment]
@raulhgit ?

**Comment by FaustinoLechuga** [comment]
Ya contacte a los usuarios a los que les afectaba este issue y se les mando una versión que de frida donde ya se resuelve este problema, estamos a la espera de la confirmación del buen funcionamiento del cambio.

**Comment by FaustinoLechuga** [comment]
Cierro el issue debido a que el usuario menciona que funciona correctamente.

**Comment by RickProductivity** [comment]
Gracias Tino
