### ISSUE TITLE
HD_Instrucción SOAP_The specified value is not a valid Host header string.

### ISSUE THREAD

**Issue by CeliaLinares** [FridaSupport/CongnitiveTestingMXTHD#5]
Al utilizar la instrucción SOAP con la siguiente sintaxis:
SOAP url={"http://0.0.0.0/webservices/services/YIFWebService"} template={"TemplateWS001.txt"} and save as WS: Running

Indica lo siguiente:
The specified value is not a valid Host header string.

(Se validó con otro WS dummy e indica lo mismo, se puede accede al WS mediante la url)

**Comment by gantonioid** [comment]
Te envié una actualización: la `v.20200207T0306` debe solucionar tu problema

**Comment by gantonioid** [comment]
@andresCruzF Turing le está pidiendo activación, nos ayudas?

**Comment by CeliaLinares** [comment]
Por favor de su apoyo compañeros, sigo sin poder utilizar la herramienta, me indica: "The owner hasn´t approved this machine, go to FRIDA to approve it"

**Comment by gantonioid** [comment]
Esto ya no se da más, cierto? para cerrar el ticket

**Comment by CeliaLinares** [comment]
Ya fue solucionado por mi parte, si no hay nada relacionado, por mí está bien.
