### ISSUE TITLE
Indica "Unexpected error" al enviar request 

### ISSUE THREAD

**Issue by CeliaLinares** [FridaSupport/CongnitiveTestingMXTHD#6]
El log indica:
"The underlying connection was closed: An unexpected error occurred on a send." 

Nota: Se valida con ws público con la misma sintaxis y si se envía.

**Comment by gantonioid** [comment]
Falta información.
De qué instrucción estás hablando?
Puedes poner aquí tu línea tal cual?

**Comment by CeliaLinares** [comment]
ID del proceso: 5590397

si uso:
SOAP url={"http://10.21.92.20:9080/yantrawebservices/services/YIFWebService/wsdl/YIFWebService.wsdl"} params={"itemuno":"877891"} template={"ReqFromSOAP.txt"} and save as WSResponse indica error 500

si uso:
SOAP url={"https://10.21.92.20:9080/yantrawebservices/services/YIFWebService/wsdl/YIFWebService.wsdl"} params={"itemuno":"877891"} template={"ReqFromSOAP.txt"} and save as WSResponse indica "Unexpected error.." (entendí por un comnetario suyo del foro, que podia afectar si era http o https)

**Comment by gantonioid** [comment]
Lo que creo es que la URL no es correcta, le estás apuntando al WSDL en sí, no a un WebService.
Dentro del WSDL se definen todos los endpoints que están disponibles. Lo que necesitas darle a la instrucción de tu script es solo uno de esos endpoints.

Tienes el WSDL que me puedas compartir?

**Comment by CeliaLinares** [comment]
Originalmente me habían compartido 2 urls, he probado con ambas y hasta ahorita me han dado el mismo resultado, entonces por tu comentario asumo que no debo utilizar la que finaliza en .wsdl:

Estas son las urls:
* http://10.21.92.20:9080/yantrawebservices/services/YIFWebService

*http://10.21.92.20:9080/yantrawebservices/services/YIFWebService/wsdl/YIFWebService.wsdl (es la que estaba en la línea que te compartí)

Duda: En que afecta el que sea http o https?

Te adjunto el contenido del wsdl :)
[DICC_WS.txt](https://github.com/FridaSupport/CongnitiveTestingMXTHD/files/4187772/DICC_WS.txt)

**Comment by gantonioid** [comment]
Si guardas ese DICC_WS.txt como DICC_WS.wsdl y creas un proyecto en SOAPUI con ese archivo, puedes ver los servicios disponibles:
![image](https://user-images.githubusercontent.com/9600868/74277015-6b018800-4cdc-11ea-98ea-8a396d8fc7a4.png)

Incluso se generan Requests de ejemplo para cada uno de los endpoints que existen.
Ahí puedes ver la URL correcta para hacer la llamada, y el body que se le debe de estar mandando
![image](https://user-images.githubusercontent.com/9600868/74277214-bc117c00-4cdc-11ea-9bbf-f9267f33b595.png)

En este caso (supongo por la url que es una dirección IP **10.21.92.20**), es un webservice en intranet. Para ellos se me haría raro que tuvieran un certificado SSL y por consecuente soportaran https.

**Comment by gantonioid** [comment]
Cada WebService tiene su propio body, puedes tomar los autogenerados con SOAPUI como ejemplo
![image](https://user-images.githubusercontent.com/9600868/74277541-583b8300-4cdd-11ea-8981-0e1bb7240329.png)

![image](https://user-images.githubusercontent.com/9600868/74277569-62f61800-4cdd-11ea-89ed-1dd17884afc8.png)

**Comment by gantonioid** [comment]
La versión `20200211T0912` Contiene ahora soporte para uso de TLS como protocolo de seguridad según la [referencia](https://stackoverflow.com/questions/32788409/c-sharp-httpwebrequest-the-underlying-connection-was-closed-an-unexpected-error/32789483)

la sintaxis ahora incluye un parámetro tls={true|false} que se encuentra documentado en la página oficial de FRIDA.

**Comment by CeliaLinares** [comment]
UPDATE: 
Cuando no se envían parámetros, con la siguiente línea:
SOAP url={"http://10.21.92.20:9080/yantrawebservices/services/YIFWebService"} template={"ReqFromSOAP.txt"} tls={true} and save as WSResponse

Se indica los siguiente: 
2/11/2020 5:43:30 PM - The params could not be parsed
2/11/2020 5:43:30 PM - Object reference not set to an instance of an object.
2/11/2020 5:43:30 PM - Exception of type 'System.Exception' was thrown.

Nota: Aplicación actualizada

**Comment by gantonioid** [comment]
Se adjunta evidencia de que con la aplicación actualizada, el error no ocurre.

[soap.zip](https://github.com/FridaSupport/CongnitiveTestingMXTHD/files/4189232/soap.zip)

**Comment by CeliaLinares** [comment]
Con la versión 206, se envió correctamente sin parámetros.
