### ISSUE TITLE
No abre URL interno https://

### ISSUE THREAD

**Issue by raulhgit** [FridaSupport/CongnitiveTestingMXTHD#8]
Al ejecutar el script **HomeDelivery MP 8085QA** ID:4612009  en Turing en el ambiente QA del Portal de compras en línea de HomeDepot aparece el siguiete error:

=========================================================
{"error":"Page could not be reached...Error: net::ERR_CERT_AUTHORITY_INVALID at  https://ecomweb1bqalv.homedepot.com.mx/"}
=========================================================

- Se está siguiendo las instrucciones indicadas el 23 de Enero por Gilberto Isida
- Se ha probado con http:// y https://
- Se probó con una versión anterior de Turing 20191111T0620 y si funciona y abre la URL
- El path del script es : Apps>THD QA>Portal Ecommerce>HomeDelivery MP 8085QA
- usuaurio raulh.gonzalez@softtek.com
- Se realizó la prueba con usuario Celia Linares y tampoco funciona con la versión 20200212T0856

**Comment by gantonioid** [comment]
Se seguirá en ticket #9
