### ISSUE TITLE
HD_Instrucción WEB2 GOTO_Page could not be reached (v20200212T0856)

### ISSUE THREAD

**Issue by CeliaLinares** [FridaSupport/CongnitiveTestingMXTHD#9]
NOTA: 
*El script contiene los pasos para ir a detalle y aceptar abrir el sitio

Usando la sintaxis:
Web2 GoTo "https://ecomweb1bqalv.homedepot.com.mx/"

El log indica:
{"error":"Page could not be reached...Error: net::ERR_CERT_AUTHORITY_INVALID at https://ecomweb1bqalv.homedepot.com.mx/"}

**Comment by gantonioid** [comment]
Se compartió un engine con el flag `ignore-certificate-errors`, y se dejó de presentar.
Ahora la navegación a esa url arroja un `Error: net::ERR_CONNECTION_TIMED_OUT`

En espera de comentarios @CeliaLinares

**Comment by gantonioid** [comment]
Lo revisamos presencialmente. La página no carga incluso de forma manual. No parece problema de FRIDA. Se probará en oficinas THD para ver si hay diferencia.

**Comment by CeliaLinares** [comment]
Validado, abre correctamente la página indicada.
